/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExchangeRateTransformation.java
 *
 * Created on 2011/3/4, 下午 03:06:01
 */

package assignment1;

/**
 *
 * @author HOME2
 */
public class ExchangeRateTransformation extends javax.swing.JFrame {

    /** Creates new form ExchangeRateTransformation */
    public ExchangeRateTransformation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCBox = new javax.swing.JComboBox();
        rCBox = new javax.swing.JComboBox();
        lTxt = new javax.swing.JTextField();
        rTxt = new javax.swing.JTextField();
        Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("匯率轉換");

        lCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Taiwan dollar", "US dollar", "China yen" }));

        rCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Taiwan dollar", "US dollar", "China yen" }));

        rTxt.setEditable(false);

        Button.setText("轉換");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(">>");

        jLabel2.setText(">>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 89, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(rCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Button)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lCBox, rCBox});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(Button)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lCBox, rCBox});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
        String ls,rs;
        double lt,rt;
        double cr = 1.0;
        ls = lCBox.getSelectedItem().toString();
        rs = rCBox.getSelectedItem().toString();
        if(ls == "Taiwan dollar"){
            if(rs == "US dollar")
                cr = 0.034064;
            else if(rs == "China yen")
                cr = 0.22378;
        }else if(ls == "US dollar"){
            if(rs == "Taiwan dollar")
                cr = 29.355;
            else if(rs == "China yen")
                cr = 6.569;
        }else if(ls == "China yen"){
            if(rs == "Taiwan dollar")
                cr = 4.4684;
            else if(rs == "US dollar")
                cr = 0.15223;
        }
        lt = Double.parseDouble(lTxt.getText());
        rt = lt * cr;
        rt = ((int)(rt * 10000)) / 10000.0;
        rTxt.setText("" + rt);
    }//GEN-LAST:event_ButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExchangeRateTransformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox lCBox;
    private javax.swing.JTextField lTxt;
    private javax.swing.JComboBox rCBox;
    private javax.swing.JTextField rTxt;
    // End of variables declaration//GEN-END:variables

}
